name: Node.js CI-CD
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 23.x
        uses: actions/setup-node@v4
        with:
          node-version: '23'
      -  name: Install dependencies and run tests
         working-directory: client
         run: npm install 

  Gitleaks-scan:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Gitleaks Setup
        uses: gitleaks/gitleaks-action@v2
      - name: Run Gitleaks Scan
        run: gitleaks detect --source ./client --report-path gitleaks-report.json
  
  Trivy-scan:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
 SonarQube-scan:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout code
        uses: actions/checkout@v4  
      - name: SonarQube Scan
        uses: sonarsource/sonarcloud-github-action@master
        with:
          projectBaseDir: './client'
          args: >
            -Dsonar.projectKey=your_project_key
            -Dsonar.organization=your_organization
            -Dsonar.sources=.
            -Dsonar.exclusions=node_modules/**,dist/**,build/**
            -Dsonar.host.url=${{ secrets.SONARHOST_URL }} 
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
          env:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 
            SONAR_HOST_URL: ${{ secrets.SONARHOST_URL }} 


        
         

